export const boxingStats = [
  {
    name: 'fights',
    value: 0,
    image: 'https://picsum.photos/200/300?image=1',
    aux1: 0,
    aux2: 0,
    group1: [],
    group2: [],
  },
  {
    name: 'wins',
    value: 0,
    image: 'https://picsum.photos/200/300?image=1',
    aux1: 0,
    aux2: 0,
    group1: [],
    group2: [],
  },
  {
    name: 'losses',
    value: 0,
    image: 'https://picsum.photos/200/300?image=1',
    aux1: 0,
    aux2: 0,
    group1: [],
    group2: [],
  },
  {
    name: 'draws',
    value: 0,
    image: 'https://picsum.photos/200/300?image=1',
    aux1: 0,
    aux2: 0,
    group1: [],
    group2: [],
  },
  {
    name: 'kos',
    value: 0,
    image: 'https://picsum.photos/200/300?image=1',
    aux1: 0,
    aux2: 0,
    group1: [],
    group2: [],
  },
];
